const challenges:challenge[] = [
    {
        title: "Ping single column coming soon page",
        img: "https://raw.githubusercontent.com/Marco90v/fontend-mentor/master/ping-coming-soon-page-master/design/desktop-design.jpg",
        linkGithub: "https://github.com/Marco90v/fontend-mentor/tree/master/ping-coming-soon-page-master",
        linkLive: "https://marco90v.github.io/fontend-mentor/ping-coming-soon-page-master/",
        description: "Chagenlle - Frontend Mentor",
        details: "This is a challenge designed by Frontend Mentor, in order to learn and improve web programming skills. The solution must be visualized as similar as possible to the image provided as the basis of the design, both for Mobile and Desktop. You can make use of any of the existing technologies to achieve the final result, as well as make use of the various platforms to deploy the solution.",
        author: "Marco Velasquez",
        skills: "HTML, CSS, Flex, Grid, JavaScript, Mobil First",
        client: "Personal"
    },
    {
        title: "Intro component with sign-up form",
        img: "https://raw.githubusercontent.com/Marco90v/fontend-mentor/master/intro-component-with-signup-form-master/design/desktop-design.jpg",
        linkGithub: "https://github.com/Marco90v/fontend-mentor/tree/master/intro-component-with-signup-form-master",
        linkLive: "https://marco90v.github.io/fontend-mentor/intro-component-with-signup-form-master/",
        description: "Chagenlle - Frontend Mentor",
        details: "This is a challenge designed by Frontend Mentor, in order to learn and improve web programming skills. The solution must be visualized as similar as possible to the image provided as the basis of the design, both for Mobile and Desktop. You can make use of any of the existing technologies to achieve the final result, as well as make use of the various platforms to deploy the solution.",
        author: "Marco Velasquez",
        skills: "HTML, CSS, Flex, JavaScript, Mobil First",
        client: "Personal"
    },
    {
        title: "Results summary component",
        img: "https://raw.githubusercontent.com/Marco90v/fontend-mentor/master/results-summary-component-main/design/desktop-design.jpg",
        linkGithub: "https://github.com/Marco90v/fontend-mentor/tree/master/results-summary-component-main",
        linkLive: "https://marco90v.github.io/fontend-mentor/results-summary-component-main/",
        description: "Chagenlle - Frontend Mentor",
        details: "This is a challenge designed by Frontend Mentor, in order to learn and improve web programming skills. The solution must be visualized as similar as possible to the image provided as the basis of the design, both for Mobile and Desktop. You can make use of any of the existing technologies to achieve the final result, as well as make use of the various platforms to deploy the solution.",
        author: "Marco Velasquez",
        skills: "HTML, CSS, Flex, Grid, JavaScript, JSON, Mobil First",
        client: "Personal"
    },
    {
        title: "Social proof section",
        img: "https://raw.githubusercontent.com/Marco90v/fontend-mentor/master/social-proof-section-master/design/desktop-design.jpg",
        linkGithub: "https://github.com/Marco90v/fontend-mentor/tree/master/social-proof-section-master",
        linkLive: "https://marco90v.github.io/fontend-mentor/social-proof-section-master/",
        description: "Chagenlle - Frontend Mentor",
        details: "This is a challenge designed by Frontend Mentor, in order to learn and improve web programming skills. The solution must be visualized as similar as possible to the image provided as the basis of the design, both for Mobile and Desktop. You can make use of any of the existing technologies to achieve the final result, as well as make use of the various platforms to deploy the solution.",
        author: "Marco Velasquez",
        skills: "HTML, CSS, Flex, Grid, Mobil First",
        client: "Personal"
    },
    {
        title: "Four card feature section",
        img: "https://raw.githubusercontent.com/Marco90v/fontend-mentor/master/four-card-feature-section-master/design/desktop-design.jpg",
        linkGithub: "https://github.com/Marco90v/fontend-mentor/tree/master/four-card-feature-section-master",
        linkLive: "https://marco90v.github.io/fontend-mentor/four-card-feature-section-master/",
        description: "Chagenlle - Frontend Mentor",
        details: "This is a challenge designed by Frontend Mentor, in order to learn and improve web programming skills. The solution must be visualized as similar as possible to the image provided as the basis of the design, both for Mobile and Desktop. You can make use of any of the existing technologies to achieve the final result, as well as make use of the various platforms to deploy the solution.",
        author: "Marco Velasquez",
        skills: "HTML, CSS, Flex, Grid, Mobil First",
        client: "Personal"
    },
    {
        title: "Single price grid component",
        img: "https://raw.githubusercontent.com/Marco90v/fontend-mentor/master/single-price-grid-component-master/design/desktop-design.jpg",
        linkGithub: "https://github.com/Marco90v/fontend-mentor/tree/master/single-price-grid-component-master",
        linkLive: "https://marco90v.github.io/fontend-mentor/single-price-grid-component-master/",
        description: "Chagenlle - Frontend Mentor",
        details: "This is a challenge designed by Frontend Mentor, in order to learn and improve web programming skills. The solution must be visualized as similar as possible to the image provided as the basis of the design, both for Mobile and Desktop. You can make use of any of the existing technologies to achieve the final result, as well as make use of the various platforms to deploy the solution.",
        author: "Marco Velasquez",
        skills: "HTML, CSS, Flex, Grid, Mobil First",
        client: "Personal"
    },
    {
        title: "Base Apparel coming soon page",
        img: "https://raw.githubusercontent.com/Marco90v/fontend-mentor/master/base-apparel-coming-soon-master/design/desktop-design.jpg",
        linkGithub: "https://github.com/Marco90v/fontend-mentor/tree/master/base-apparel-coming-soon-master",
        linkLive: "https://marco90v.github.io/fontend-mentor/base-apparel-coming-soon-master/",
        description: "Chagenlle - Frontend Mentor",
        details: "This is a challenge designed by Frontend Mentor, in order to learn and improve web programming skills. The solution must be visualized as similar as possible to the image provided as the basis of the design, both for Mobile and Desktop. You can make use of any of the existing technologies to achieve the final result, as well as make use of the various platforms to deploy the solution.",
        author: "Marco Velasquez",
        skills: "HTML, CSS, JavaScript Grid, Flex, Mobil First",
        client: "Personal"
    },
    {
        title: "3 Column preview card component main/",
        img: "https://raw.githubusercontent.com/Marco90v/fontend-mentor/master/3-column-preview-card-component-main/design/desktop-design.jpg",
        linkGithub: "https://github.com/Marco90v/fontend-mentor/tree/master/3-column-preview-card-component-main",
        linkLive: "https://marco90v.github.io/fontend-mentor/3-column-preview-card-component-main/",
        description: "Chagenlle - Frontend Mentor",
        details: "This is a challenge designed by Frontend Mentor, in order to learn and improve web programming skills. The solution must be visualized as similar as possible to the image provided as the basis of the design, both for Mobile and Desktop. You can make use of any of the existing technologies to achieve the final result, as well as make use of the various platforms to deploy the solution.",
        author: "Marco Velasquez",
        skills: "HTML, CSS, Flex Grid, Mobil First",
        client: "Personal"
    },
    {
        title: "Profile card component",
        img: "https://raw.githubusercontent.com/Marco90v/fontend-mentor/master/profile-card-component-main/design/desktop-design.jpg",
        linkGithub: "https://github.com/Marco90v/fontend-mentor/tree/master/profile-card-component-main",
        linkLive: "https://marco90v.github.io/fontend-mentor/profile-card-component-main/",
        description: "Chagenlle - Frontend Mentor",
        details: "This is a challenge designed by Frontend Mentor, in order to learn and improve web programming skills. The solution must be visualized as similar as possible to the image provided as the basis of the design, both for Mobile and Desktop. You can make use of any of the existing technologies to achieve the final result, as well as make use of the various platforms to deploy the solution.",
        author: "Marco Velasquez",
        skills: "HTML, CSS, Flex Grid, Mobil First",
        client: "Personal"
    },
    {
        title: "Stats preview card component",
        img: "https://raw.githubusercontent.com/Marco90v/fontend-mentor/master/stats-preview-card-component-main/design/desktop-design.jpg",
        linkGithub: "https://github.com/Marco90v/fontend-mentor/tree/master/stats-preview-card-component-main",
        linkLive: "https://marco90v.github.io/fontend-mentor/stats-preview-card-component-main/",
        description: "Chagenlle - Frontend Mentor",
        details: "This is a challenge designed by Frontend Mentor, in order to learn and improve web programming skills. The solution must be visualized as similar as possible to the image provided as the basis of the design, both for Mobile and Desktop. You can make use of any of the existing technologies to achieve the final result, as well as make use of the various platforms to deploy the solution.",
        author: "Marco Velasquez",
        skills: "HTML, CSS, Grid, Mobil First",
        client: "Personal"
    },
    {
        title: "Huddle landing page with a single introductory section",
        img: "https://raw.githubusercontent.com/Marco90v/fontend-mentor/master/huddle-landing-page-with-single-introductory-section-master/design/desktop-design.jpg",
        linkGithub: "https://github.com/Marco90v/fontend-mentor/tree/master/huddle-landing-page-with-single-introductory-section-master",
        linkLive: "https://marco90v.github.io/fontend-mentor/huddle-landing-page-with-single-introductory-section-master/",
        description: "Chagenlle - Frontend Mentor",
        details: "This is a challenge designed by Frontend Mentor, in order to learn and improve web programming skills. The solution must be visualized as similar as possible to the image provided as the basis of the design, both for Mobile and Desktop. You can make use of any of the existing technologies to achieve the final result, as well as make use of the various platforms to deploy the solution.",
        author: "Marco Velasquez",
        skills: "HTML, CSS, Grid, Mobil First",
        client: "Personal"
    },
    {
        title: "Interactive rating component",
        img: "https://raw.githubusercontent.com/Marco90v/fontend-mentor/master/interactive-rating-component-main/design/desktop-design.jpg",
        linkGithub: "https://github.com/Marco90v/fontend-mentor/tree/master/interactive-rating-component-main",
        linkLive: "https://marco90v.github.io/fontend-mentor/interactive-rating-component-main/",
        description: "Chagenlle - Frontend Mentor",
        details: "This is a challenge designed by Frontend Mentor, in order to learn and improve web programming skills. The solution must be visualized as similar as possible to the image provided as the basis of the design, both for Mobile and Desktop. You can make use of any of the existing technologies to achieve the final result, as well as make use of the various platforms to deploy the solution.",
        author: "Marco Velasquez",
        skills: "HTML, CSS, JavaScript Grid, Mobil First",
        client: "Personal"
    },
    {
        title: "NFT preview card component",
        img: "https://raw.githubusercontent.com/Marco90v/fontend-mentor/master/nft-preview-card-component-main/design/desktop-design.jpg",
        linkGithub: "https://github.com/Marco90v/fontend-mentor/tree/master/nft-preview-card-component-main",
        linkLive: "https://marco90v.github.io/fontend-mentor/nft-preview-card-component-main/",
        description: "Chagenlle - Frontend Mentor",
        details: "This is a challenge designed by Frontend Mentor, in order to learn and improve web programming skills. The solution must be visualized as similar as possible to the image provided as the basis of the design, both for Mobile and Desktop. You can make use of any of the existing technologies to achieve the final result, as well as make use of the various platforms to deploy the solution.",
        author: "Marco Velasquez",
        skills: "HTML, CSS, Grid, Mobil First",
        client: "Personal"
    },
    {
        title: "Order summary card",
        img: "https://raw.githubusercontent.com/Marco90v/fontend-mentor/master/order-summary-component-main/design/desktop-design.jpg",
        linkGithub: "https://github.com/Marco90v/fontend-mentor/tree/master/order-summary-component-main",
        linkLive: "https://marco90v.github.io/fontend-mentor/order-summary-component-main/",
        description: "Chagenlle - Frontend Mentor",
        details: "This is a challenge designed by Frontend Mentor, in order to learn and improve web programming skills. The solution must be visualized as similar as possible to the image provided as the basis of the design, both for Mobile and Desktop. You can make use of any of the existing technologies to achieve the final result, as well as make use of the various platforms to deploy the solution.",
        author: "Marco Velasquez",
        skills: "HTML, CSS, Grid, Mobil First",
        client: "Personal"
    },
    {
        title: "Product preview card component",
        img: "https://raw.githubusercontent.com/Marco90v/fontend-mentor/master/product-preview-card-component-main/design/desktop-design.jpg",
        linkGithub: "https://github.com/Marco90v/fontend-mentor/tree/master/product-preview-card-component-main",
        linkLive: "https://marco90v.github.io/fontend-mentor/product-preview-card-component-main/",
        description: "Chagenlle - Frontend Mentor",
        details: "This is a challenge designed by Frontend Mentor, in order to learn and improve web programming skills. The solution must be visualized as similar as possible to the image provided as the basis of the design, both for Mobile and Desktop. You can make use of any of the existing technologies to achieve the final result, as well as make use of the various platforms to deploy the solution.",
        author: "Marco Velasquez",
        skills: "HTML, CSS, Grid, Mobil First",
        client: "Personal"
    },
    {
        title: "QR code component",
        img: "https://raw.githubusercontent.com/Marco90v/fontend-mentor/master/qr-code-component-main/design/desktop-design.jpg",
        linkGithub: "https://github.com/Marco90v/fontend-mentor/tree/master/qr-code-component-main",
        linkLive: "https://marco90v.github.io/fontend-mentor/qr-code-component-main/",
        description: "Chagenlle - Frontend Mentor",
        details: "This is a challenge designed by Frontend Mentor, in order to learn and improve web programming skills. The solution must be visualized as similar as possible to the image provided as the basis of the design, both for Mobile and Desktop. You can make use of any of the existing technologies to achieve the final result, as well as make use of the various platforms to deploy the solution.",
        author: "Marco Velasquez",
        skills: "HTML, CSS, Grid, Mobil First",
        client: "Personal"
    },
    {
        title: "Intro section with dropdown navigation",
        img: "https://raw.githubusercontent.com/Marco90v/intro-section-with-dropdown-navigation-main/master/design/desktop-design.jpg",
        linkGithub: "https://github.com/Marco90v/intro-section-with-dropdown-navigation-main",
        linkLive: "https://marco90v.github.io/intro-section-with-dropdown-navigation-main/",
        description: "Chagenlle - Frontend Mentor",
        details: "This is a challenge designed by Frontend Mentor, in order to learn and improve web programming skills. The solution must be visualized as similar as possible to the image provided as the basis of the design, both for Mobile and Desktop. You can make use of any of the existing technologies to achieve the final result, as well as make use of the various platforms to deploy the solution.",
        author: "Marco Velasquez",
        skills: "HTML, CSS, JavaScript, Mobil First",
        client: "Personal"
    },
    {
        title: "Advice generator app",
        img: "https://raw.githubusercontent.com/Marco90v/advice-generator-app-main/master/design/desktop-design.jpg",
        linkGithub: "https://github.com/Marco90v/advice-generator-app-main",
        linkLive: "https://marco90v.github.io/advice-generator-app-main/",
        description: "Chagenlle - Frontend Mentor",
        details: "This is a challenge designed by Frontend Mentor, in order to learn and improve web programming skills. The solution must be visualized as similar as possible to the image provided as the basis of the design, both for Mobile and Desktop. You can make use of any of the existing technologies to achieve the final result, as well as make use of the various platforms to deploy the solution.",
        author: "Marco Velasquez",
        skills: "HTML, CSS, JavaScript, flex, Mobil First",
        client: "Personal"
    },
    {
        title: "Time tracking dashboard",
        img: "https://raw.githubusercontent.com/Marco90v/time-tracking-dashboard-main/master/design/desktop-design.jpg",
        linkGithub: "https://github.com/Marco90v/time-tracking-dashboard-main",
        linkLive: "https://marco90v.github.io/time-tracking-dashboard-main/",
        description: "Chagenlle - Frontend Mentor",
        details: "This is a challenge designed by Frontend Mentor, in order to learn and improve web programming skills. The solution must be visualized as similar as possible to the image provided as the basis of the design, both for Mobile and Desktop. You can make use of any of the existing technologies to achieve the final result, as well as make use of the various platforms to deploy the solution.",
        author: "Marco Velasquez",
        skills: "HTML, CSS, JavaScript, flex, Mobil First",
        client: "Personal"
    },
    {
        title: "Article preview component",
        img: "https://raw.githubusercontent.com/Marco90v/article-preview-component-master/master/design/desktop-design.jpg",
        linkGithub: "https://github.com/Marco90v/article-preview-component-master",
        linkLive: "https://marco90v.github.io/article-preview-component-master",
        description: "Chagenlle - Frontend Mentor",
        details: "This is a challenge designed by Frontend Mentor, in order to learn and improve web programming skills. The solution must be visualized as similar as possible to the image provided as the basis of the design, both for Mobile and Desktop. You can make use of any of the existing technologies to achieve the final result, as well as make use of the various platforms to deploy the solution.",
        author: "Marco Velasquez",
        skills: "HTML, CSS, JavaScript, flex, Grid, Mobil First",
        client: "Personal"
    },
    {
        title: "Tip calculator app",
        img: "https://raw.githubusercontent.com/Marco90v/tip-calculator-app-main/master/design/desktop-design-completed.jpg",
        linkGithub: "https://github.com/Marco90v/tip-calculator-app-main",
        linkLive: "https://marco90v.github.io/tip-calculator-app-main",
        description: "Chagenlle - Frontend Mentor",
        details: "This is a challenge designed by Frontend Mentor, in order to learn and improve web programming skills. The solution must be visualized as similar as possible to the image provided as the basis of the design, both for Mobile and Desktop. You can make use of any of the existing technologies to achieve the final result, as well as make use of the various platforms to deploy the solution.",
        author: "Marco Velasquez",
        skills: "HTML, CSS, JavaScript, Grid, Mobil First",
        client: "Personal"
    },
    {
        title: "FAQ accordion card",
        img: "https://raw.githubusercontent.com/Marco90v/faq-accordion-card-main/master/design/desktop-design.jpg",
        linkGithub: "https://github.com/Marco90v/faq-accordion-card-main",
        linkLive: "https://marco90v.github.io/faq-accordion-card-main",
        description: "Chagenlle - Frontend Mentor",
        details: "This is a challenge designed by Frontend Mentor, in order to learn and improve web programming skills. The solution must be visualized as similar as possible to the image provided as the basis of the design, both for Mobile and Desktop. You can make use of any of the existing technologies to achieve the final result, as well as make use of the various platforms to deploy the solution.",
        author: "Marco Velasquez",
        skills: "HTML, CSS, JavaScript, Flex, transition, Mobil First",
        client: "Personal"
    },
    {
        title: "Expenses Chart Component Main",
        img: "https://raw.githubusercontent.com/Marco90v/expenses-chart-component-main/master/design/desktop-design.jpg",
        linkGithub: "https://github.com/Marco90v/expenses-chart-component-main",
        linkLive: "https://marco90v.github.io/expenses-chart-component-main/",
        description: "Chagenlle - Frontend Mentor",
        details: "This is a challenge designed by Frontend Mentor, in order to learn and improve web programming skills. The solution must be visualized as similar as possible to the image provided as the basis of the design, both for Mobile and Desktop. You can make use of any of the existing technologies to achieve the final result, as well as make use of the various platforms to deploy the solution.",
        author: "Marco Velasquez",
        skills: "HTML, CSS, JavaScript, Flex, Grid, Fetch, Mobil First",
        client: "Personal"
    },
];

export { challenges };